import type { ServiceIcon } from "@/lib/firestore-types";

export type ServiceIconOption = {
  value: ServiceIcon;
  label: string;
  iconifyName: string;
};

const PREFIX = "lucide:";

/** Map ServiceIcon value to Iconify icon name (e.g. "lucide:home"). */
const ICONIFY_MAP: Record<ServiceIcon, string> = {
  roof: `${PREFIX}home`,
  gutter: `${PREFIX}droplets`,
  repair: `${PREFIX}wrench`,
  inspection: `${PREFIX}clipboard-check`,
  maintenance: `${PREFIX}settings`,
  emergency: `${PREFIX}circle-alert`,
  strata: `${PREFIX}building-2`,
  home: `${PREFIX}home`,
  building: `${PREFIX}building`,
  "building-2": `${PREFIX}building-2`,
  hammer: `${PREFIX}hammer`,
  paintbrush: `${PREFIX}paintbrush`,
  ruler: `${PREFIX}ruler`,
  shield: `${PREFIX}shield`,
  "shield-check": `${PREFIX}shield-check`,
  thermometer: `${PREFIX}thermometer`,
  snowflake: `${PREFIX}snowflake`,
  wind: `${PREFIX}wind`,
  sun: `${PREFIX}sun`,
  droplet: `${PREFIX}droplet`,
  wrench: `${PREFIX}wrench`,
  "clipboard-check": `${PREFIX}clipboard-check`,
  settings: `${PREFIX}settings`,
  "alert-circle": `${PREFIX}circle-alert`,
  key: `${PREFIX}key`,
  lightbulb: `${PREFIX}lightbulb`,
  "file-check": `${PREFIX}file-check`,
  eye: `${PREFIX}eye`,
  package: `${PREFIX}package`,
  truck: `${PREFIX}truck`,
  phone: `${PREFIX}phone`,
  mail: `${PREFIX}mail`,
  "map-pin": `${PREFIX}map-pin`,
  leaf: `${PREFIX}leaf`,
  "tree-pine": `${PREFIX}trees`,
  zap: `${PREFIX}zap`,
  "circle-check": `${PREFIX}circle-check`,
  star: `${PREFIX}star`,
  flame: `${PREFIX}flame`,
  layers: `${PREFIX}layers`,
  box: `${PREFIX}box`,
  "ruler-pencil": `${PREFIX}pen-ruler`,
  "hard-hat": `${PREFIX}hard-hat`,
  brush: `${PREFIX}paintbrush`,
  "spray-can": `${PREFIX}spray-can`,
  droplets: `${PREFIX}droplets`,
  "cloud-rain": `${PREFIX}cloud-rain`,
  "sun-snow": `${PREFIX}sun-snow`,
  "badge-check": `${PREFIX}badge-check`,
  award: `${PREFIX}award`,
  "heart-handshake": `${PREFIX}heart-handshake`,
  tool: `${PREFIX}tool`,
  screwdriver: `${PREFIX}screwdriver`,
  drill: `${PREFIX}drill`,
  "tape-measure": `${PREFIX}ruler`,
  "clipboard-list": `${PREFIX}clipboard-list`,
  "file-text": `${PREFIX}file-text`,
  calendar: `${PREFIX}calendar`,
  clock: `${PREFIX}clock`,
  users: `${PREFIX}users`,
  "user-check": `${PREFIX}user-check`,
  briefcase: `${PREFIX}briefcase`,
  receipt: `${PREFIX}receipt`,
  "message-square": `${PREFIX}message-square`,
  camera: `${PREFIX}camera`,
  image: `${PREFIX}image`,
  palette: `${PREFIX}palette`,
  scissors: `${PREFIX}scissors`,
  "pen-tool": `${PREFIX}pen-tool`,
  bookmark: `${PREFIX}bookmark`,
  tag: `${PREFIX}tag`,
  link: `${PREFIX}link`,
  "external-link": `${PREFIX}external-link`,
  "arrow-right": `${PREFIX}arrow-right`,
  "thumbs-up": `${PREFIX}thumbs-up`,
  "hand-heart": `${PREFIX}hand-heart`,
  "circle-dot": `${PREFIX}circle-dot`,
  "square-check": `${PREFIX}square-check`,
  gauge: `${PREFIX}gauge`,
  battery: `${PREFIX}battery`,
  plug: `${PREFIX}plug`,
  "plug-zap": `${PREFIX}plug-zap`,
  umbrella: `${PREFIX}umbrella`,
  cloud: `${PREFIX}cloud`,
  "cloud-sun": `${PREFIX}cloud-sun`,
  "cloud-lightning": `${PREFIX}cloud-lightning`,
  "thermometer-sun": `${PREFIX}thermometer-sun`,
  "droplet-off": `${PREFIX}droplet-off`,
  "shield-alert": `${PREFIX}shield-alert`,
  "shield-off": `${PREFIX}shield-off`,
  "check-square": `${PREFIX}check-square`,
  "list-checks": `${PREFIX}list-checks`,
  clipboard: `${PREFIX}clipboard`,
  "file-plus": `${PREFIX}file-plus`,
  folder: `${PREFIX}folder`,
  archive: `${PREFIX}archive`,
  inbox: `${PREFIX}inbox`,
  send: `${PREFIX}send`,
  quote: `${PREFIX}quote`,
  "message-circle": `${PREFIX}message-circle`,
  "phone-call": `${PREFIX}phone-call`,
  headphones: `${PREFIX}headphones`,
  bell: `${PREFIX}bell`,
  megaphone: `${PREFIX}megaphone`,
};

const LABELS: Record<ServiceIcon, string> = {
  roof: "Roof",
  gutter: "Gutter",
  repair: "Repair",
  inspection: "Inspection",
  maintenance: "Maintenance",
  emergency: "Emergency",
  strata: "Strata",
  home: "Home",
  building: "Building",
  "building-2": "Building 2",
  hammer: "Hammer",
  paintbrush: "Paintbrush",
  ruler: "Ruler",
  shield: "Shield",
  "shield-check": "Shield check",
  thermometer: "Thermometer",
  snowflake: "Snowflake",
  wind: "Wind",
  sun: "Sun",
  droplet: "Droplet",
  wrench: "Wrench",
  "clipboard-check": "Clipboard check",
  settings: "Settings",
  "alert-circle": "Alert",
  key: "Key",
  lightbulb: "Lightbulb",
  "file-check": "File check",
  eye: "Eye",
  package: "Package",
  truck: "Truck",
  phone: "Phone",
  mail: "Mail",
  "map-pin": "Map pin",
  leaf: "Leaf",
  "tree-pine": "Trees",
  zap: "Zap",
  "circle-check": "Circle check",
  star: "Star",
  flame: "Flame",
  layers: "Layers",
  box: "Box",
  "ruler-pencil": "Pen ruler",
  "hard-hat": "Hard hat",
  brush: "Brush",
  "spray-can": "Spray can",
  droplets: "Droplets",
  "cloud-rain": "Cloud rain",
  "sun-snow": "Sun snow",
  "badge-check": "Badge check",
  award: "Award",
  "heart-handshake": "Heart handshake",
  tool: "Tool",
  screwdriver: "Screwdriver",
  drill: "Drill",
  "tape-measure": "Tape measure",
  "clipboard-list": "Clipboard list",
  "file-text": "File text",
  calendar: "Calendar",
  clock: "Clock",
  users: "Users",
  "user-check": "User check",
  briefcase: "Briefcase",
  receipt: "Receipt",
  "message-square": "Message square",
  camera: "Camera",
  image: "Image",
  palette: "Palette",
  scissors: "Scissors",
  "pen-tool": "Pen tool",
  bookmark: "Bookmark",
  tag: "Tag",
  link: "Link",
  "external-link": "External link",
  "arrow-right": "Arrow right",
  "thumbs-up": "Thumbs up",
  "hand-heart": "Hand heart",
  "circle-dot": "Circle dot",
  "square-check": "Square check",
  gauge: "Gauge",
  battery: "Battery",
  plug: "Plug",
  "plug-zap": "Plug zap",
  umbrella: "Umbrella",
  cloud: "Cloud",
  "cloud-sun": "Cloud sun",
  "cloud-lightning": "Cloud lightning",
  "thermometer-sun": "Thermometer sun",
  "droplet-off": "Droplet off",
  "shield-alert": "Shield alert",
  "shield-off": "Shield off",
  "check-square": "Check square",
  "list-checks": "List checks",
  clipboard: "Clipboard",
  "file-plus": "File plus",
  folder: "Folder",
  archive: "Archive",
  inbox: "Inbox",
  send: "Send",
  quote: "Quote",
  "message-circle": "Message circle",
  "phone-call": "Phone call",
  headphones: "Headphones",
  bell: "Bell",
  megaphone: "Megaphone",
};

/** All service icon options for pickers, in display order. */
export const SERVICE_ICON_OPTIONS: ServiceIconOption[] = (
  Object.keys(ICONIFY_MAP) as ServiceIcon[]
).map((value) => ({
  value,
  label: LABELS[value],
  iconifyName: ICONIFY_MAP[value],
}));

/** Resolve a stored ServiceIcon (or legacy string) to its Iconify name for AppIcon. */
export function getServiceIconifyName(icon: ServiceIcon | string): string {
  const key = icon as ServiceIcon;
  return (key in ICONIFY_MAP ? ICONIFY_MAP[key] : null) ?? ICONIFY_MAP.roof;
}
