/**
 * Sydney and greater NSW suburbs for address/suburb autocomplete.
 * No API key required.
 */
export const SUBURBS: string[] = [
  "Alexandria",
  "Annandale",
  "Ashfield",
  "Auburn",
  "Bankstown",
  "Barangaroo",
  "Balmain",
  "Bondi",
  "Bondi Junction",
  "Botany",
  "Brookvale",
  "Burwood",
  "Cabramatta",
  "Cammeray",
  "Campbelltown",
  "Canterbury",
  "Castle Hill",
  "Chatswood",
  "Chippendale",
  "Concord",
  "Cronulla",
  "Darlinghurst",
  "Darling Point",
  "Double Bay",
  "Drummoyne",
  "Eastgardens",
  "Eastwood",
  "Epping",
  "Erskineville",
  "Fairfield",
  "Forestville",
  "Frenchs Forest",
  "Glebe",
  "Gladesville",
  "Gordon",
  "Granville",
  "Greenwich",
  "Hornsby",
  "Hurstville",
  "Kensington",
  "Kingsford",
  "Kings Cross",
  "Kirrawee",
  "Kogarah",
  "Lane Cove",
  "Leichhardt",
  "Liverpool",
  "Macquarie Park",
  "Maroubra",
  "Marrickville",
  "Mascot",
  "Merrylands",
  "Miranda",
  "Mosman",
  "Neutral Bay",
  "Newtown",
  "North Sydney",
  "North Ryde",
  "North Parramatta",
  "Parramatta",
  "Paddington",
  "Penrith",
  "Petersham",
  "Potts Point",
  "Pyrmont",
  "Randwick",
  "Redfern",
  "Rhodes",
  "Rockdale",
  "Rose Bay",
  "Rosebery",
  "Rozelle",
  "Ryde",
  "St Leonards",
  "St Peters",
  "Surry Hills",
  "Sutherland",
  "Sydney",
  "Sydney Olympic Park",
  "Tamworth",
  "Tempe",
  "Ultimo",
  "Vaucluse",
  "Waterloo",
  "Waverley",
  "Wentworthville",
  "Willoughby",
  "Wollongong",
  "Woollahra",
  "Woolooware",
  "Zetland",
].sort();

const SUBURBS_LOWER = SUBURBS.map((s) => s.toLowerCase());

export function filterSuburbs(query: string, limit = 10): string[] {
  const q = query.trim().toLowerCase();
  if (q.length < 2) return [];
  const startsWith: string[] = [];
  const includes: string[] = [];
  for (let i = 0; i < SUBURBS.length; i++) {
    if (SUBURBS_LOWER[i].startsWith(q)) startsWith.push(SUBURBS[i]);
    else if (SUBURBS_LOWER[i].includes(q)) includes.push(SUBURBS[i]);
  }
  return [...startsWith, ...includes].slice(0, limit);
}
